[[redirects]]
from = "/presentations/ar-the-next-big-thing/static/*"
to = "https://ar-the-next-big-thing.netlify.app/static/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
