[[redirects]]
  from = "/presentations/ar-the-next-big-thing/*"
  to = "https://ar-the-next-big-thing.netlify.app/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
